tegra_camera: fix building error when disable CONFIG_TEGRA_CAMERA
  LD      vmlinux.o
drivers/built-in.o: In function `is_tegra_camera_on':
/home/roc/Work/bug_vip/source_vibrante/kernel/include/media/
tegra_camera.h:59: multiple definition of `is_tegra_camera_on'
arch/arm/mach-tegra/built-in.o:/home/roc/Work/bug_vip/source_vibrante
/kernel/include/media/tegra_camera.h:59: first defined here
make: *** [vmlinux.o] Error 1

Commit '678708d WAR: gr3d: limit 3d clock when camera is on'
introduced a function is_tegra_camera_on(), which is dummy when
CONFIG_TEGRA_CAMERA is disabled. But it will be multiple defined
when includ this header file in multiple C files.

So marking it as static will kill this error.

Change-Id: I9dbcf1231f744c23e761d70da0bfc874fb286e4a
Signed-off-by: Bryan Wu <pengw@nvidia.com>
Reviewed-on: http://git-master/r/167510
Reviewed-by: Automatic_Commit_Validation_User
GVS: Gerrit_Virtual_Submit
Reviewed-by: Winnie Hsu <whsu@nvidia.com>